initial cut at panos_import
mrichardson03/mrichardson03.panos pull request #68
Opened 2021-04-28 19:50 UTC by nembery

initial version of panos_import module for issue #31 

Note that there still needs to be an argspec defined for the module. I can add this as another PR in the future, or we can hold off on this PR until that is done and committed. In theory, that should be straightforward, I just haven't had the cycles to implement it yet.

2021-05-01 17:55 UTC, mrichardson03 requested changes
I think this should be done as a module.  Import actions are low level and largely independent from other operations, and don't need long term job monitoring like a software install.  They're also easier to cover with unit tests.

2021-05-01 17:55 UTC, mrichardson03 commented on plugins/httpapi/panos.py
> +    def import_file(self, filename, category):
Let's keep the methods named the same as the XML-API command types, so `import()`.

2021-05-01 17:55 UTC, mrichardson03 commented on plugins/httpapi/panos.py
> +        r = requests.post(url, params=params, files=files, verify=False)
Did you ever try this with the standard `send_request()` method?  I'm not opposed to using `requests` since it is included in the Ansible virtualenv by default, but I feel like this is simple enough it could be done.

2021-05-01 17:55 UTC, mrichardson03 commented on plugins/action/panos_import.py
> +# pylint: skip-file
Everything should go through pylint.

2021-05-03 14:11 UTC, nembery commented on plugins/httpapi/panos.py
> +        r = requests.post(url, params=params, files=files, verify=False)
The issue is you have to build a multipart/form-data and calculate boundary strings and lots of fun stuff that requests does for you. This is especially important if you are importing a software package or any largish binary file.

2021-05-03 14:24 UTC, mrichardson03 commented on plugins/httpapi/panos.py
> +        r = requests.post(url, params=params, files=files, verify=False)
Yeah, that's a good point.  I was asking out of curiosity more than anything.  It won't be able to reuse the TCP session from Ansible, but since import is one big request it won't matter much.

2022-03-17 13:43 UTC, closed without merging